# Generated by Django 3.0.3 on 2020-03-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Poster'),
        ),
    ]
