# Generated by Django 3.0.3 on 2020-03-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteka', '0002_auto_20200302_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Poster'),
        ),
    ]
