# Generated by Django 3.0.3 on 2020-03-02 21:46

from django.db import migrations, models
import filmoteka.models


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteka', '0003_auto_20200302_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=filmoteka.models.image_path, verbose_name='Poster'),
        ),
    ]
