# Generated by Django 3.0.3 on 2020-03-09 20:07

from django.db import migrations, models
import django.db.models.deletion
import filmoteka.models


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteka', '0005_auto_20200302_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genres',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(null=True, upload_to=filmoteka.models.attachement_path, verbose_name='File')),
                ('type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='image', help_text='Type of attachment', max_length=5, verbose_name='Type of attachment')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmoteka.Film')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
